name: Cypress Tests

on: [push]

jobs:
    cypress-run:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install dependencies
              run: npm install

            - name: Run Cypress
              run: npx cypress run
